FROM node:20
RUN apt-get update -y && \
  apt-get install -y ca-certificates tzdata

WORKDIR /app

COPY package.json pnpm-lock.yaml .npmrc ./
COPY src/syncer/postgres/prisma ./src/syncer/postgres/prisma
RUN npm i -g corepack@latest && corepack enable
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile && pnpm run prisma:generate
COPY . .
