FROM node:18
RUN apt-get update -y && \
  apt-get install -y ca-certificates tzdata

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable && corepack install
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY . .
