services:
  syncer:
    build:
      dockerfile: Dockerfile.syncer
    restart: always
    environment:
      ENVIRONMENT: testnet-preprod
      OGMIOS_HOST: ogmios
      OGMIOS_PORT: 1337
      REDIS_URL: redis://default:minswap@redis:6379
      POSTGRES_URL: postgresql://postgres:minswap@postgres:5432/syncer?schema=public&connection_limit=5
      SYNC_START_POINT: "7790880c9f0ff09990f253dd1bf1a55d2a2e5340bf694e5c0bb166439e513e45.10918782"
    command: pnpm run syncer:start

  redis:
    image: redis:7
    restart: always
    command: --requirepass minswap
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: syncer
      POSTGRES_PASSWORD: minswap
    volumes:
      - ./src/syncer/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ogmios:
    platform: linux/amd64
    image: cardanosolutions/ogmios:v6.5.0
    restart: always
    command: [ "--host", "0.0.0.0", "--node-socket", "/node.socket", "--node-config", "/configs/${OGMIOS_ENVIRONMENT}/config.json" ]
    ports:
      - 1337:1337
    volumes:
      - type: bind
        source: $CARDANO_NODE_SOCKET_PATH
        target: /node.socket
      - type: bind
        source: ./node-configs
        target: /configs

volumes:
  redis-data: {}
  postgres-data: {}
